### PR TITLE
initial commit of k8s configs

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@TuanDQ-Tuev-Sued,

You can follow this PR to track progress for publishing this new website!

@fredg02 @mbarbero,
I need your help with replacing the current openPASS website (https://openpass.eclipse.org/) with this new Hugo website: https://eclipsefdn-openpass.netlify.app/

This PR defines the k8s files that you can use to deploy this service. I created a Jenkins instance for this site here: https://foundation.eclipse.org/ci/webdev/job/openpass.eclipse.org/

Finally, I added the Jenkins webhook to this github repository.

Please let me know if you need anything else from me or if you need me to do anything else to get this done!

Cheers,

**Comment by mbarbero** [comment]
@chrisguindon Everything looks good to me. Let me know once you've merged this PR and we will deploy the website on the cluster. Then, reverse proxy needs to be changed to point to new location. Will you submit a patch to the nginx config?

PS: you mentioned _Jenkins instance_, but it's a _Jenkins **job**_

**Comment by chrisguindon** [comment]
> Will you submit a patch to the nginx config?

@mbarbero I created a patch for Nginx!  
https://foundation.eclipse.org/r/c/puppet/modules/+/4051

I will let you merge this when you are ready to deploy this to production.

Thanks!

**Comment by mbarbero** [comment]
BTW, there is no Jenkinfile in the repo, so the build job will not work. Please open a separate PR with one.

**Comment by chrisguindon** [comment]
@mbarbero Done https://github.com/EclipseFdn/openpass.eclipse.org/pull/62

Let me know if you need anything else!

**Pull request merged**
